# Generated by Django 4.0.8 on 2024-06-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='tiltle',
            new_name='title',
        ),
    ]
